// <auto-generated />
using System;
using HT.Agent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace HT.Agent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914144311_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HT.Agent.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_session_id");

                    b.Property<string>("ActiveTerminalId")
                        .HasColumnType("text")
                        .HasColumnName("active_terminal_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerNo")
                        .HasColumnType("text")
                        .HasColumnName("customer_no");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("text")
                        .HasColumnName("employee_no");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_at");

                    b.Property<Guid?>("PasswordResetBy")
                        .HasColumnType("uuid")
                        .HasColumnName("password_reset_by");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_app_user_company_id");

                    b.HasIndex("CustomerNo")
                        .HasDatabaseName("ix_app_user_customer_no");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_user_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("TerminalId")
                        .HasColumnType("text")
                        .HasColumnName("terminal_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id", "At")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("Action", "At")
                        .HasDatabaseName("ix_audit_log_action_at");

                    b.HasIndex("UserId", "At")
                        .HasDatabaseName("ix_audit_log_user_id_at");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<bool?>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Target")
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_backup_run");

                    b.ToTable("backup_run");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Chunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bbox")
                        .HasColumnType("text")
                        .HasColumnName("bbox");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("KbId")
                        .HasColumnType("uuid")
                        .HasColumnName("kb_id");

                    b.Property<int?>("PageNo")
                        .HasColumnType("integer")
                        .HasColumnName("page_no");

                    b.Property<int>("ParseVersion")
                        .HasColumnType("integer")
                        .HasColumnName("parse_version");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("SectionPath")
                        .HasColumnType("text")
                        .HasColumnName("section_path");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_chunk");

                    b.HasIndex("DocId")
                        .HasDatabaseName("ix_chunk_doc_id");

                    b.HasIndex("KbId", "Classification")
                        .HasDatabaseName("ix_chunk_kb_id_classification");

                    b.ToTable("chunk");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Clause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_clause");

                    b.HasIndex("Category", "Code")
                        .HasDatabaseName("ix_clause_category_code");

                    b.ToTable("clause");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_company_code");

                    b.ToTable("company");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.CustomerDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomerNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_no");

                    b.Property<DateOnly?>("DeliveredAt")
                        .HasColumnType("date")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeviceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_no");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("ProjectNo")
                        .HasColumnType("text")
                        .HasColumnName("project_no");

                    b.HasKey("Id")
                        .HasName("pk_customer_device");

                    b.HasIndex("CustomerNo", "DeviceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_device_customer_no_device_no");

                    b.ToTable("customer_device");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.DocMetadata", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("DocCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_category");

                    b.Property<string>("DocVersion")
                        .HasColumnType("text")
                        .HasColumnName("doc_version");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProjectNo")
                        .HasColumnType("text")
                        .HasColumnName("project_no");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("DocumentId")
                        .HasName("pk_doc_metadata");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("ix_doc_metadata_customer_name");

                    b.HasIndex("ProjectNo")
                        .HasDatabaseName("ix_doc_metadata_project_no");

                    b.ToTable("doc_metadata");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChunkStrategyOverride")
                        .HasColumnType("text")
                        .HasColumnName("chunk_strategy_override");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_withdrawn");

                    b.Property<Guid>("KbId")
                        .HasColumnType("uuid")
                        .HasColumnName("kb_id");

                    b.Property<string>("ParseError")
                        .HasColumnType("text")
                        .HasColumnName("parse_error");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parse_status");

                    b.Property<int>("ParseVersion")
                        .HasColumnType("integer")
                        .HasColumnName("parse_version");

                    b.Property<DateTimeOffset?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("KbId", "Classification", "ParseStatus")
                        .HasDatabaseName("ix_document_kb_id_classification_parse_status");

                    b.ToTable("document");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.FaultCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlarmCode")
                        .HasColumnType("text")
                        .HasColumnName("alarm_code");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<string>("CauseAnalysis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause_analysis");

                    b.Property<long?>("ChunkId")
                        .HasColumnType("bigint")
                        .HasColumnName("chunk_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("Phenomenon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phenomenon");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("SourceCompany")
                        .HasColumnType("text")
                        .HasColumnName("source_company");

                    b.Property<string>("SpareParts")
                        .HasColumnType("text")
                        .HasColumnName("spare_parts");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fault_case");

                    b.HasIndex("CaseNo")
                        .IsUnique()
                        .HasDatabaseName("ix_fault_case_case_no");

                    b.HasIndex("SyncStatus")
                        .HasDatabaseName("ix_fault_case_sync_status");

                    b.HasIndex("DeviceModel", "AlarmCode")
                        .HasDatabaseName("ix_fault_case_device_model_alarm_code");

                    b.ToTable("fault_case");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.GenerationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseProjectNo")
                        .HasColumnType("text")
                        .HasColumnName("base_project_no");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("OutputFileKey")
                        .HasColumnType("text")
                        .HasColumnName("output_file_key");

                    b.Property<string>("ProjectHint")
                        .HasColumnType("text")
                        .HasColumnName("project_hint");

                    b.Property<string>("SlotValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slot_values");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_generation_session");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_generation_session_template_id");

                    b.ToTable("generation_session");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultChunkStrategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_chunk_strategy");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_base");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_knowledge_base_company_id");

                    b.HasIndex("Tier", "CompanyId")
                        .HasDatabaseName("ix_knowledge_base_tier_company_id");

                    b.ToTable("knowledge_base");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.ParseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long?>("ChunkId")
                        .HasColumnType("bigint")
                        .HasColumnName("chunk_id");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<Guid>("QueuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("queued_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_parse_job");

                    b.HasIndex("DocId")
                        .HasDatabaseName("ix_parse_job_doc_id");

                    b.HasIndex("Status", "QueuedAt")
                        .HasDatabaseName("ix_parse_job_status_queued_at");

                    b.ToTable("parse_job");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Project", b =>
                {
                    b.Property<string>("ProjectNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project_no");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("ContractAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("contract_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("text")
                        .HasColumnName("delivery_status");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("DocPath")
                        .HasColumnType("text")
                        .HasColumnName("doc_path");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SpecParams")
                        .HasColumnType("text")
                        .HasColumnName("spec_params");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("ProjectNo")
                        .HasName("pk_project");

                    b.HasIndex("CustomerName", "Year", "DeviceType")
                        .HasDatabaseName("ix_project_customer_name_year_device_type");

                    b.ToTable("project");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.PublishRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("PublicDocId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_doc_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_key");

                    b.Property<Guid>("SourceDocId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_doc_id");

                    b.Property<string>("WithdrawReason")
                        .HasColumnType("text")
                        .HasColumnName("withdraw_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnBy")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by");

                    b.HasKey("Id")
                        .HasName("pk_publish_record");

                    b.ToTable("publish_record");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.QaMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("FeedbackReason")
                        .HasColumnType("text")
                        .HasColumnName("feedback_reason");

                    b.Property<bool?>("Helpful")
                        .HasColumnType("boolean")
                        .HasColumnName("helpful");

                    b.Property<string>("Intent")
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("NoResultHints")
                        .HasColumnType("text")
                        .HasColumnName("no_result_hints");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("RewrittenQuery")
                        .HasColumnType("text")
                        .HasColumnName("rewritten_query");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Sources")
                        .HasColumnType("jsonb")
                        .HasColumnName("sources");

                    b.HasKey("Id")
                        .HasName("pk_qa_message");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_qa_message_session_id");

                    b.ToTable("qa_message");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.QaSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_qa_session");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_qa_session_user_id_updated_at");

                    b.ToTable("qa_session");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classifications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("classifications");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.ToTable("role");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_no");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<bool?>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_sync_log");

                    b.ToTable("sync_log");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.SysConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_sys_config");

                    b.ToTable("sys_config");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_template");

                    b.ToTable("template");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.TemplateSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Choices")
                        .HasColumnType("jsonb")
                        .HasColumnName("choices");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<bool>("ForbidInherit")
                        .HasColumnType("boolean")
                        .HasColumnName("forbid_inherit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("SubFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("sub_fields");

                    b.Property<string>("SuggestSource")
                        .HasColumnType("text")
                        .HasColumnName("suggest_source");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_template_slot");

                    b.HasIndex("TemplateId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_template_slot_template_id_tag");

                    b.ToTable("template_slot");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("en");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<string>("Zh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zh");

                    b.HasKey("Id")
                        .HasName("pk_term");

                    b.HasIndex("Domain", "Zh")
                        .HasDatabaseName("ix_term_domain_zh");

                    b.ToTable("term");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_no");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DeviceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Updates")
                        .HasColumnType("jsonb")
                        .HasColumnName("updates");

                    b.HasKey("Id")
                        .HasName("pk_ticket");

                    b.HasIndex("CustomerNo")
                        .HasDatabaseName("ix_ticket_customer_no");

                    b.HasIndex("TicketNo")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_ticket_no");

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.UserTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastIp")
                        .HasColumnType("text")
                        .HasColumnName("last_ip");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terminal_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_terminal");

                    b.HasIndex("UserId", "TerminalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_terminal_user_id_terminal_id");

                    b.ToTable("user_terminal");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.VocabTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasColumnType("text")
                        .HasColumnName("aliases");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("VocabKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vocab_key");

                    b.HasKey("Id")
                        .HasName("pk_vocab_term");

                    b.HasIndex("VocabKey", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_vocab_term_vocab_key_value");

                    b.ToTable("vocab_term");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user__companies_company_id");

                    b.HasOne("HT.Agent.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_user__roles_role_id");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Chunk", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Document", "Doc")
                        .WithMany()
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk__documents_doc_id");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.DocMetadata", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Document", "Document")
                        .WithOne("Metadata")
                        .HasForeignKey("HT.Agent.Domain.Entities.DocMetadata", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doc_metadata__documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Document", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.KnowledgeBase", "Kb")
                        .WithMany()
                        .HasForeignKey("KbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document__knowledge_bases_kb_id");

                    b.Navigation("Kb");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.GenerationSession", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_session__templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_knowledge_base_company_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.ParseJob", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Document", "Doc")
                        .WithMany()
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parse_job_document_doc_id");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.QaMessage", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.QaSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qa_message__qa_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.TemplateSlot", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.Template", "Template")
                        .WithMany("Slots")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_slot_template_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.UserTerminal", b =>
                {
                    b.HasOne("HT.Agent.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_terminal_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Document", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.QaSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HT.Agent.Domain.Entities.Template", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
