using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HT.Agent.Infrastructure.Persistence.Migrations
{
    /// <summary>模型之外的数据库结构（7.2）：
    /// 1. audit_log 重建为按月分区表——审计只写不改、量大，分区避免单表膨胀影响查询；
    /// 2. chunk.embedding 的 HNSW 近似索引（cosine）——类型与参数须随语料规模重评，此处为默认值；
    /// 3. chunk.search_text 的 simple 全文 GIN 表达式索引——查询侧必须使用完全相同的表达式才走索引。</summary>
    public partial class AuditPartitionAndSearchIndexes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE audit_log;

                CREATE SEQUENCE audit_log_id_seq;

                -- 分区键必须在主键内，故主键为 (id, at)；id 用序列默认值（PG16 分区表不支持 identity）
                CREATE TABLE audit_log (
                    id bigint NOT NULL DEFAULT nextval('audit_log_id_seq'),
                    at timestamptz NOT NULL,
                    user_id uuid NULL,
                    username text NOT NULL,
                    company_id uuid NULL,
                    action text NOT NULL,
                    target_type text NULL,
                    target_id text NULL,
                    detail jsonb NULL,
                    result text NOT NULL,
                    ip text NULL,
                    terminal_id text NULL,
                    CONSTRAINT pk_audit_log PRIMARY KEY (id, at)
                ) PARTITION BY RANGE (at);

                ALTER SEQUENCE audit_log_id_seq OWNED BY audit_log.id;

                CREATE INDEX ix_audit_log_at ON audit_log (at);
                CREATE INDEX ix_audit_log_user_id_at ON audit_log (user_id, at);
                CREATE INDEX ix_audit_log_action_at ON audit_log (action, at);

                -- 兜底分区：新月份分区没来得及建时写入不失败（审计一条都不能丢）
                CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT;

                -- 预建 48 个月分区（2025-01 起）；后续月份由运维批次的分区维护任务滚动创建
                DO $$
                DECLARE
                    m date := date '2025-01-01';
                BEGIN
                    FOR i IN 0..47 LOOP
                        EXECUTE format(
                            'CREATE TABLE %I PARTITION OF audit_log FOR VALUES FROM (%L) TO (%L)',
                            'audit_log_' || to_char(m, 'YYYYMM'), m, m + interval '1 month');
                        m := m + interval '1 month';
                    END LOOP;
                END $$;
                """);

            // 近似最近邻（7.2）：候选先取后过滤会因权限过滤导致返回不足，
            // 组合 btree (kb_id, classification) 已由模型迁移创建；HNSW 负责向量路
            migrationBuilder.Sql(
                "CREATE INDEX ix_chunk_embedding_hnsw ON chunk USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);");

            // 关键词路（7.2）：simple 解析器 + 应用侧二元分词。检索 SQL 使用同一表达式
            migrationBuilder.Sql(
                "CREATE INDEX ix_chunk_search_text_fts ON chunk USING gin (to_tsvector('simple', search_text));");

            // 中文 LIKE 兜底
            migrationBuilder.Sql(
                "CREATE INDEX ix_chunk_text_trgm ON chunk USING gin (text gin_trgm_ops);");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS ix_chunk_text_trgm;
                DROP INDEX IF EXISTS ix_chunk_search_text_fts;
                DROP INDEX IF EXISTS ix_chunk_embedding_hnsw;
                DROP TABLE audit_log;
                CREATE TABLE audit_log (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    at timestamptz NOT NULL,
                    user_id uuid NULL,
                    username text NOT NULL,
                    company_id uuid NULL,
                    action text NOT NULL,
                    target_type text NULL,
                    target_id text NULL,
                    detail jsonb NULL,
                    result text NOT NULL,
                    ip text NULL,
                    terminal_id text NULL,
                    CONSTRAINT pk_audit_log PRIMARY KEY (id, at)
                );
                CREATE INDEX ix_audit_log_at ON audit_log (at);
                CREATE INDEX ix_audit_log_user_id_at ON audit_log (user_id, at);
                CREATE INDEX ix_audit_log_action_at ON audit_log (action, at);
                """);
        }
    }
}
